<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E6ML15705" ignored="2" name="Selenium" tests="2" failures="1" timestamp="16 Feb 2020 06:00:03 GMT" time="19.139" errors="0">
  <testcase name="verifyApplicationInNewTab" time="0.412" classname="test.BookMyFurnitureTestCases">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at pages.HomePage.openApplicationInNewTab(HomePage.java:58)
at test.BookMyFurnitureTestCases.verifyApplicationInNewTab(BookMyFurnitureTestCases.java:49)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyApplicationInNewTab -->
  <testcase name="verifyApplicationInNewWindow" time="2.615" classname="test.BookMyFurnitureTestCases"/>
  <testcase name="bookAFurniture" time="0.0" classname="test.BookMyFurnitureTestCases">
    <ignored/>
  </testcase> <!-- bookAFurniture -->
  <testcase name="validateCredentials" time="0.0" classname="test.BookMyFurnitureTestCases">
    <ignored/>
  </testcase> <!-- validateCredentials -->
</testsuite> <!-- Selenium -->
